AAfrag: AAfrag202.f90 user202.f90 
	gfortran -O -o AAfrag.out AAfrag202.f90 user202.f90 

clean:
	-rm AAfrag.out spectra.mod
	-rm spec_nu_tot spec_aprot spec_aneut spec_adeut spec_elpos spec_gam \
		spec_ahel spec_nu
